name: flutter_starter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  upgrader: ^11.4.0
  flutter_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  generate: true
