name: Build

on:
  pull_request:
    branches:
      - 'dependabot/**'
  push:
    branches:
      - 'dependabot/**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Max Java version supported by Flutter (oneMajorVersionHigherJavaVersion - 1): 23
      # https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle_utils.dart
      # Java version bundled with Android Studio (Meerkat): 21
      # Update gradle-wrapper.properties accordingly
      # https://docs.gradle.org/current/userguide/compatibility.html#java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Refresh Flutter packages
        run: |
          flutter clean
          flutter pub get

      - name: Build Android App
        run: flutter build appbundle --debug

      - name: Build iOS App
        run: flutter build ios --no-codesign
